### ISSUE TITLE
My flypad keep shuting down

### ISSUE THREAD

**Issue by paulporto** [lonestar125/parrot_flypad_pc#1]
i just got a flypad in the mail. im trying to read its bytes over usb to see if i can use it in a project.
so far the output seem very simple to decode, but i have a problem. after 15 seconds of connecting the usb cable the device seem to disconnect or shutdown. i cant find a way to keep it working. do i have to send it a byte or something?

```
device0="/dev/input/by-id/usb-Parrot_FLYPAD_Controller-event-joystick"
device1="/dev/input/by-id/usb-Parrot_FLYPAD_Controller-joystick"

f = open(device0,"rb")
h = ""
while True:
	#print(hex(int.from_bytes(f.read(1),byteorder='big'))) 
	#print(hex(int.from_bytes(f.read(1),byteorder='little'))) 
	h = ""
	bs = f.read(8)

	for b in bs:
		h += hex(b)[2:] + "\t"
	print(h)
```

**Comment by paulporto** [comment]
thanks for publishing your findings. hope you have a minute to check my problem.

**Comment by lonestar125** [comment]
Hello, from what ive seen (forum posts i read before making this project) no one seems to have figured out how to get the controller to not disconnect over usb. My project uses bluetooth (ble) exclusively so im not sure how usb would work.

**Comment by lonestar125** [comment]
what do the outputted bytes from usb look like? 

edit: Did a quick sweep of various forum posts and still nothing, monitoring the bytes sent and received when connecting the controller to your computer might give you something that can be manually re sent every 10-15 seconds although im not sure how you would go about monitoring that. Im willing to help you if you find anything you think is substantial enough to be a lead just reply to this issue.

**Comment by paulporto** [comment]
i will try sending bytes to the device and see what happens. wish me luck
